// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/myComponents/Alert/Alert.vue')['default']
    Button: typeof import('./src/components/myComponents/mode/Button.vue')['default']
    Color: typeof import('./src/components/myComponents/mode/Color.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Error: typeof import('./src/components/Error.vue')['default']
    Form: typeof import('./src/components/myComponents/Form/Form.vue')['default']
    Input: typeof import('./src/components/myComponents/mode/Input.vue')['default']
    Number: typeof import('./src/components/myComponents/mode/Number.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/myComponents/mode/Select.vue')['default']
    Switch: typeof import('./src/components/myComponents/mode/Switch.vue')['default']
    Table: typeof import('./src/components/myComponents/Table.vue')['default']
    Tour: typeof import('./src/components/Tour.vue')['default']
    Verify: typeof import('./src/components/verifition/Verify.vue')['default']
  }
}
